"use client";

import React, { useState, useEffect } from "react";
import { Party, PartyType, PaymentTerm } from "@/types/shipment";
import { partyService } from "services/partyService";
import { INDIAN_STATES, getStateByGstNo } from "@/utils/indianStates";
import { Users, X, AlertTriangle } from "lucide-react";

interface PartyModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSaved: () => void;
  initialParty?: Party | null;
}

export default function PartyModal({ isOpen, onClose, onSaved, initialParty }: PartyModalProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(true);
  const [partyType, setPartyType] = useState<PartyType>(PartyType.Both);
  const [gstNo, setGstNo] = useState("");
  const [panNo, setPanNo] = useState("");
  const [contactPerson, setContactPerson] = useState("");
  const [email, setEmail] = useState("");
  const [mobile, setMobile] = useState("");
  const [phone, setPhone] = useState("");
  const [address, setAddress] = useState("");
  const [city, setCity] = useState("");
  const [state, setState] = useState("Maharashtra");
  const [pincode, setPincode] = useState("");
  const [defaultPaymentTerm, setDefaultPaymentTerm] = useState<PaymentTerm>(PaymentTerm.ToPay);
  const [creditLimit, setCreditLimit] = useState<number>(0);
  const [isActive, setIsActive] = useState(true);

  // Auto-generate alias helper
  const generateAlias = (partyName: string): string => {
    if (!partyName.trim()) return "";
    const clean = partyName.replace(/[^a-zA-Z0-9\s]/g, "").trim();
    const words = clean.split(/\s+/).filter(Boolean);
    if (words.length === 0) return "";
    if (words.length === 1) {
      const w = words[0].toUpperCase();
      return w.slice(0, 6);
    }
    if (words.length === 2) {
      const p1 = words[0].toUpperCase().slice(0, 3);
      const p2 = words[1].toUpperCase().slice(0, 3);
      return `${p1}-${p2}`;
    }
    const initials = words.slice(0, 3).map((w) => w[0].toUpperCase()).join("");
    const lastWord = words[words.length - 1].toUpperCase().slice(0, 4);
    return `${initials}-${lastWord}`;
  };

  useEffect(() => {
    if (initialParty) {
      setName(initialParty.name || "");
      setCode(initialParty.code || "");
      setIsCodeAutoGenerated(false);
      setPartyType(initialParty.partyType ?? PartyType.Both);
      setGstNo(initialParty.gstNo || "");
      setPanNo(initialParty.panNo || "");
      setContactPerson(initialParty.contactPerson || "");
      setEmail(initialParty.email || "");
      setMobile(initialParty.mobile || "");
      setPhone(initialParty.phone || "");
      setAddress(initialParty.address || "");
      setCity(initialParty.city || "");
      setState(initialParty.state || "Maharashtra");
      setPincode(initialParty.pincode || "");
      setDefaultPaymentTerm(initialParty.defaultPaymentTerm ?? PaymentTerm.ToPay);
      setCreditLimit(initialParty.creditLimit || 0);
      setIsActive(initialParty.isActive ?? true);
    } else {
      resetForm();
    }
  }, [initialParty, isOpen]);

  const resetForm = () => {
    setName("");
    setCode("");
    setIsCodeAutoGenerated(true);
    setPartyType(PartyType.Both);
    setGstNo("");
    setPanNo("");
    setContactPerson("");
    setEmail("");
    setMobile("");
    setPhone("");
    setAddress("");
    setCity("");
    setState("Maharashtra");
    setPincode("");
    setDefaultPaymentTerm(PaymentTerm.ToPay);
    setCreditLimit(0);
    setIsActive(true);
    setError("");
  };

  const handleNameChange = (val: string) => {
    setName(val);
    if (isCodeAutoGenerated || !code.trim()) {
      setCode(generateAlias(val));
    }
  };

  const handleGstChange = (val: string) => {
    const upper = val.toUpperCase().replace(/[^0-9A-Z]/g, "").slice(0, 15);
    setGstNo(upper);

    // Auto extract PAN if 15 chars (chars 3 to 12 in GSTIN is PAN)
    if (upper.length >= 12 && (!panNo || panNo === upper.slice(2, 12))) {
      setPanNo(upper.slice(2, 12));
    }

    // Auto-detect State from GST 2-digit prefix
    if (upper.length >= 2) {
      const matchState = getStateByGstNo(upper);
      if (matchState) {
        setState(matchState.name);
      }
    }
  };

  const handlePanChange = (val: string) => {
    const upper = val.toUpperCase().replace(/[^0-9A-Z]/g, "").slice(0, 10);
    setPanNo(upper);
  };

  const handleMobileChange = (val: string) => {
    const digitsOnly = val.replace(/\D/g, "").slice(0, 10);
    setMobile(digitsOnly);
  };

  const handlePincodeChange = (val: string) => {
    const digitsOnly = val.replace(/\D/g, "").slice(0, 6);
    setPincode(digitsOnly);
  };

  if (!isOpen) return null;

  const validateForm = (): string | null => {
    if (!name.trim()) return "Company / Party Name is required.";
    
    // Allowed characters: letters, numbers, spaces, and . , & - ' ( ) / #
    const nameRegex = /^[a-zA-Z0-9\s\.\,\&\-\'\(\)\/\#]+$/;
    if (!nameRegex.test(name.trim())) {
      return "Party Name contains invalid special characters. Only letters, numbers, spaces, and . , & - ' ( ) / # are allowed.";
    }

    // GST validation if provided
    if (gstNo.trim()) {
      const gstRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
      if (!gstRegex.test(gstNo.trim())) {
        return "Invalid GSTIN format. Expected 15 characters (e.g. 27AAAAA0000A1Z5).";
      }
    }

    // PAN validation if provided
    if (panNo.trim()) {
      const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
      if (!panRegex.test(panNo.trim())) {
        return "Invalid PAN format. Expected 10 alphanumeric characters (e.g. AAAAA0000A).";
      }
    }

    // Mobile validation if provided
    if (mobile.trim()) {
      if (mobile.trim().length !== 10) {
        return "Mobile Number must be exactly 10 digits.";
      }
      if (!/^[6-9]\d{9}$/.test(mobile.trim())) {
        return "Mobile Number must start with 6, 7, 8, or 9 (valid Indian mobile number).";
      }
    }

    // Email validation if provided
    if (email.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email.trim())) {
        return "Please enter a valid email address (e.g. name@company.com).";
      }
    }

    // Pincode validation if provided
    if (pincode.trim()) {
      if (pincode.trim().length !== 6 || !/^\d{6}$/.test(pincode.trim())) {
        return "Pincode must be exactly 6 numeric digits.";
      }
    }

    return null;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const valError = validateForm();
    if (valError) {
      setError(valError);
      return;
    }

    try {
      setLoading(true);
      setError("");

      const finalCode = code.trim() || generateAlias(name) || undefined;

      const payload: Partial<Party> = {
        name: name.trim(),
        code: finalCode,
        partyType,
        gstNo: gstNo.trim().toUpperCase() || undefined,
        panNo: panNo.trim().toUpperCase() || undefined,
        contactPerson: contactPerson.trim() || undefined,
        email: email.trim() || undefined,
        mobile: mobile.trim() || undefined,
        phone: phone.trim() || undefined,
        address: address.trim() || undefined,
        city: city.trim() || undefined,
        state: state.trim() || undefined,
        pincode: pincode.trim() || undefined,
        defaultPaymentTerm,
        creditLimit: Number(creditLimit) || 0,
        isActive,
      };

      if (initialParty?.id) {
        await partyService.updateParty(initialParty.id, payload);
      } else {
        await partyService.createParty(payload);
      }

      onSaved();
      onClose();
    } catch (err: any) {
      console.error("Save party error:", err);
      setError(err?.message || "Failed to save Party. Please check details.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-[#D9E2E3] dark:border-slate-800 w-full max-w-2xl overflow-hidden my-8 animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="px-6 py-4 border-b border-[#E5EAEB] dark:border-slate-800 flex items-center justify-between bg-white dark:bg-slate-900">
          <div>
            <h2 className="text-base font-bold text-[#111827] dark:text-white flex items-center gap-2">
              <span className="p-1.5 bg-[#E7F1F2] text-[#2F8E86] rounded-lg">
                <Users className="w-4 h-4 text-[#2F8E86]" />
              </span>
              <span>{initialParty ? "Edit Master Party / Customer" : "Add New Master Party (Consignor / Consignee)"}</span>
            </h2>
            <p className="text-xs text-[#64748B] dark:text-slate-400 mt-0.5">
              Maintain company directory with automated alias, GST & PAN formatting.
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-[#94A3B8] hover:text-[#111827] dark:hover:text-white p-1.5 rounded-lg hover:bg-[#F7F8F8] dark:hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && (
            <div className="p-3 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 rounded-lg text-red-700 dark:text-red-300 text-xs font-semibold flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-[#D95C5C] shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {/* Party Type & Basic Info */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="sm:col-span-2">
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1">
                Company / Party Name *
              </label>
              <input
                type="text"
                required
                placeholder="e.g. ABC Cargo & Logistics Ltd."
                value={name}
                onChange={(e) => handleNameChange(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-semibold text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-bold text-[#111827] dark:text-slate-300">
                  Party Alias / Code
                </label>
                <span className="text-[10px] text-[#2F8E86] font-semibold">Auto-generated</span>
              </div>
              <input
                type="text"
                placeholder="e.g. ABC-LOG"
                value={code}
                onChange={(e) => {
                  setCode(e.target.value.toUpperCase());
                  setIsCodeAutoGenerated(false);
                }}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-[#2F8E86] placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>
          </div>

          {/* Role Type & Default Term */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-[#F7F8F8] dark:bg-slate-800/40 p-3.5 rounded-xl border border-[#E5EAEB] dark:border-slate-800">
            <div>
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1.5">
                Party Role (Interchangeable)
              </label>
              <div className="grid grid-cols-3 gap-1.5">
                {[
                  { value: PartyType.Both, label: "Both (Recommended)" },
                  { value: PartyType.Consignor, label: "Consignor (Sender)" },
                  { value: PartyType.Consignee, label: "Consignee (Receiver)" },
                ].map((item) => (
                  <button
                    key={item.value}
                    type="button"
                    onClick={() => setPartyType(item.value)}
                    className={`py-1.5 px-2 rounded-lg text-[11px] font-bold border transition text-center cursor-pointer ${
                      partyType === item.value
                        ? "bg-[#2F8E86] text-white border-[#2F8E86] shadow-2xs"
                        : "bg-white dark:bg-slate-800 text-[#64748B] dark:text-slate-300 border-[#D9E2E3] dark:border-slate-700 hover:bg-[#F5FAFA]"
                    }`}
                  >
                    {item.label}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1.5">
                Default Payment Term
              </label>
              <select
                value={defaultPaymentTerm}
                onChange={(e) => setDefaultPaymentTerm(Number(e.target.value))}
                className="w-full h-9 px-3 py-1.5 border border-[#D9E2E3] dark:border-slate-700 rounded-lg text-xs font-semibold bg-white dark:bg-slate-900 text-[#111827] dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86] cursor-pointer"
              >
                <option value={PaymentTerm.ToPay}>To Pay (Consignee Paid)</option>
                <option value={PaymentTerm.Paid}>Paid (Consignor Paid)</option>
                <option value={PaymentTerm.TBB}>T.B.B. (To Be Billed / Credit)</option>
              </select>
            </div>
          </div>

          {/* Tax Identification (GSTIN & PAN) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-bold text-[#111827] dark:text-slate-300">
                  GSTIN (15 Digits)
                </label>
                <span className="text-[10px] text-[#94A3B8]">e.g. 27AAACB1234F1Z1</span>
              </div>
              <input
                type="text"
                maxLength={15}
                placeholder="27AAACB1234F1Z1"
                value={gstNo}
                onChange={(e) => handleGstChange(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86] uppercase"
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-bold text-[#111827] dark:text-slate-300">
                  PAN Number (10 Chars)
                </label>
                <span className="text-[10px] text-[#94A3B8]">e.g. AAACB1234F</span>
              </div>
              <input
                type="text"
                maxLength={10}
                placeholder="AAACB1234F"
                value={panNo}
                onChange={(e) => handlePanChange(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86] uppercase"
              />
            </div>
          </div>

          {/* Contacts (Person, Mobile, Email) */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1">
                Contact Person
              </label>
              <input
                type="text"
                placeholder="e.g. Rajesh Sharma"
                value={contactPerson}
                onChange={(e) => setContactPerson(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-medium text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-bold text-[#111827] dark:text-slate-300">
                  Mobile (10 Digits)
                </label>
                <span className="text-[10px] text-[#94A3B8] font-mono">
                  {mobile.length}/10
                </span>
              </div>
              <input
                type="tel"
                maxLength={10}
                placeholder="9876543210"
                value={mobile}
                onChange={(e) => handleMobileChange(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1">
                Email Address
              </label>
              <input
                type="email"
                placeholder="billing@abccargo.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-medium text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>
          </div>

          {/* Address */}
          <div>
            <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1">
              Premises / Street Address
            </label>
            <input
              type="text"
              placeholder="Plot 45, Industrial Area, Phase II"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-medium text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
            />
          </div>

          {/* City, State Dropdown, Pincode (6 digits) */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1">
                City
              </label>
              <input
                type="text"
                placeholder="e.g. Pune"
                value={city}
                onChange={(e) => setCity(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-medium text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-[#111827] dark:text-slate-300 mb-1">
                State (GST State Code)
              </label>
              <select
                value={state}
                onChange={(e) => setState(e.target.value)}
                className="w-full h-10 px-3 py-2 border border-[#D9E2E3] dark:border-slate-700 rounded-xl text-xs font-semibold bg-white dark:bg-slate-900 text-[#111827] dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86] cursor-pointer"
              >
                {INDIAN_STATES.map((s) => (
                  <option key={s.code} value={s.name}>
                    [{s.code}] {s.name}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-bold text-[#111827] dark:text-slate-300">
                  Pincode (6 Digits)
                </label>
                <span className="text-[10px] text-[#94A3B8] font-mono">
                  {pincode.length}/6
                </span>
              </div>
              <input
                type="text"
                maxLength={6}
                placeholder="411018"
                value={pincode}
                onChange={(e) => handlePincodeChange(e.target.value)}
                className="w-full h-10 px-3.5 py-2 border border-[#D9E2E3] dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-[#111827] dark:text-white placeholder:text-[#94A3B8] focus:outline-none focus:ring-2 focus:ring-[#2F8E86]/20 focus:border-[#2F8E86]"
              />
            </div>
          </div>

          {/* Footer Actions */}
          <div className="pt-4 border-t border-[#E5EAEB] dark:border-slate-800 flex items-center justify-between">
            <label className="flex items-center gap-2 text-xs font-semibold text-[#64748B] dark:text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={isActive}
                onChange={(e) => setIsActive(e.target.checked)}
                className="rounded text-[#2F8E86] focus:ring-[#2F8E86]"
              />
              <span>Active in Autocomplete Directory</span>
            </label>

            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={onClose}
                className="btn-secondary"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading}
                className="btn-primary"
              >
                {loading ? "Saving..." : initialParty ? "Update Party" : "Save Master Party"}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
