"use client";

import React, { useState, useEffect } from "react";
import { LocationMaster } from "@/types/shipment";
import { fleetService } from "services/fleetService";
import { INDIAN_STATES } from "@/utils/indianStates";
import { MapPin, X, AlertTriangle } from "lucide-react";

interface LocationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSaved: () => void;
  initialLocation?: LocationMaster | null;
}

function toTitleCase(str: string): string {
  return str.replace(/\w\S*/g, (txt) => txt.charAt(0).toUpperCase() + txt.substring(1).toLowerCase());
}

export default function LocationModal({
  isOpen,
  onClose,
  onSaved,
  initialLocation,
}: LocationModalProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(true);
  const [city, setCity] = useState("");
  const [state, setState] = useState("Bihar");
  const [address, setAddress] = useState("");
  const [pincode, setPincode] = useState("");
  const [isActive, setIsActive] = useState(true);

  // Auto-generate station code
  const generateStationCode = (stationName: string): string => {
    if (!stationName.trim()) return "";
    const clean = stationName.replace(/[^a-zA-Z0-9\s]/g, "").trim();
    const words = clean.split(/\s+/).filter(Boolean);
    if (words.length === 0) return "";
    if (words.length === 1) {
      return words[0].toUpperCase().slice(0, 4);
    }
    if (words.length === 2) {
      const p1 = words[0].toUpperCase().slice(0, 3);
      const p2 = words[1].toUpperCase().slice(0, 3);
      return `${p1}-${p2}`;
    }
    const initials = words.slice(0, 3).map((w) => w[0].toUpperCase()).join("");
    return `${initials}-HUB`;
  };

  useEffect(() => {
    if (isOpen) {
      if (initialLocation) {
        setName(initialLocation.name || "");
        setCode(initialLocation.code || "");
        setIsCodeAutoGenerated(false);
        setCity(initialLocation.city || "");
        setState(initialLocation.state || "Bihar");
        setAddress(initialLocation.address || "");
        setPincode(initialLocation.pincode || "");
        setIsActive(initialLocation.isActive ?? true);
      } else {
        resetForm();
      }
    }
  }, [isOpen, initialLocation]);

  const resetForm = () => {
    setName("");
    setCode("");
    setIsCodeAutoGenerated(true);
    setCity("");
    setState("Bihar");
    setAddress("");
    setPincode("");
    setIsActive(true);
    setError("");
  };

  const handleNameChange = (val: string) => {
    const formatted = toTitleCase(val);
    setName(formatted);
    if (isCodeAutoGenerated || !code.trim()) {
      setCode(generateStationCode(val));
    }
  };

  const handlePincodeChange = (val: string) => {
    const digitsOnly = val.replace(/\D/g, "").slice(0, 6);
    setPincode(digitsOnly);
  };

  if (!isOpen) return null;

  const validateForm = (): string | null => {
    if (!name.trim()) return "Station / Hub Name is required.";

    const nameRegex = /^[a-zA-Z0-9\s\.\,\&\-\'\(\)\/\#]+$/;
    if (!nameRegex.test(name.trim())) {
      return "Station Name contains invalid characters.";
    }

    if (pincode.trim()) {
      if (pincode.trim().length !== 6 || !/^\d{6}$/.test(pincode.trim())) {
        return "Pincode must be exactly 6 numeric digits (below 6 digits is not allowed).";
      }
    }

    return null;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const valError = validateForm();
    if (valError) {
      setError(valError);
      return;
    }

    try {
      setLoading(true);
      setError("");

      const finalCode = code.trim() || generateStationCode(name) || "HUB";

      const payload: Partial<LocationMaster> = {
        name: toTitleCase(name.trim()),
        code: finalCode.toUpperCase(),
        city: city.trim() ? toTitleCase(city.trim()) : undefined,
        state: state.trim() || undefined,
        address: address.trim() ? toTitleCase(address.trim()) : undefined,
        pincode: pincode.trim() || undefined,
        isActive,
      };

      if (initialLocation && initialLocation.id) {
        await fleetService.updateLocation(initialLocation.id, payload);
      } else {
        await fleetService.createLocation(payload);
      }
      onSaved();
      onClose();
    } catch (err: any) {
      console.error("Save location error:", err);
      setError(err?.message || "Failed to save station / location.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 w-full max-w-md overflow-hidden my-6 animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-sky-50/50 dark:bg-slate-800/60">
          <div>
            <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <MapPin className="w-4 h-4 text-sky-600 dark:text-sky-400" />
              <span>{initialLocation ? "Edit Station / Hub" : "Add Station / Operating Hub"}</span>
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Manage booking stations, transit nodes, and routing destinations.
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 dark:hover:text-white p-1.5 rounded-lg transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[80vh] overflow-y-auto">
          {error && (
            <div className="p-3 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 rounded-lg text-red-700 dark:text-red-300 text-xs font-semibold flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-red-600 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
              Station / Hub Name * (Capitalized)
            </label>
            <input
              type="text"
              required
              placeholder="e.g. Pahari Patna Hub or Mumbai Central"
              value={name}
              onChange={(e) => handleNameChange(e.target.value)}
              className="w-full h-10 px-3.5 py-2 border border-slate-300 dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-semibold text-slate-900 dark:text-white capitalize focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>

          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Station Code / Short Code (ALL CAPS)
              </label>
              <span className="text-[10px] text-sky-600 dark:text-sky-400 font-semibold">Auto-generated</span>
            </div>
            <input
              type="text"
              placeholder="e.g. PAT-HUB or MUM"
              value={code}
              onChange={(e) => {
                setCode(e.target.value.toUpperCase());
                setIsCodeAutoGenerated(false);
              }}
              className="w-full h-10 px-3.5 py-2 border border-slate-300 dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-sky-700 dark:text-sky-400 uppercase focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                City (Capitalized)
              </label>
              <input
                type="text"
                placeholder="e.g. Patna"
                value={city}
                onChange={(e) => setCity(toTitleCase(e.target.value))}
                className="w-full h-10 px-3.5 py-2 border border-slate-300 dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-medium text-slate-900 dark:text-white capitalize focus:outline-none focus:ring-2 focus:ring-sky-500"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                State (GST State Code)
              </label>
              <select
                value={state}
                onChange={(e) => setState(e.target.value)}
                className="w-full h-10 px-3 py-2 border border-slate-300 dark:border-slate-700 rounded-xl text-xs font-semibold bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-sky-500 cursor-pointer"
              >
                {INDIAN_STATES.map((s) => (
                  <option key={s.code} value={s.name}>
                    [{s.code}] {s.name}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
              Hub / Station Street Address
            </label>
            <textarea
              rows={2}
              placeholder="e.g. Transport Nagar, Near Ring Road"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              className="w-full px-3.5 py-2 border border-slate-300 dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-medium text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>

          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Pincode (6 Digits)
              </label>
              <span className="text-[10px] text-slate-400 font-mono">
                {pincode.length}/6
              </span>
            </div>
            <input
              type="text"
              maxLength={6}
              placeholder="800007"
              value={pincode}
              onChange={(e) => handlePincodeChange(e.target.value)}
              className="w-full h-10 px-3.5 py-2 border border-slate-300 dark:border-slate-700 dark:bg-slate-900 rounded-xl text-xs font-mono font-bold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>

          {/* Footer Actions */}
          <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
            <label className="flex items-center gap-2 text-xs font-semibold text-slate-700 dark:text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={isActive}
                onChange={(e) => setIsActive(e.target.checked)}
                className="rounded text-sky-600 focus:ring-sky-500"
              />
              <span>Active in Routing Dropdowns</span>
            </label>

            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold rounded-xl text-xs transition cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading}
                className="px-5 py-2 bg-sky-600 hover:bg-sky-700 text-white font-bold rounded-xl text-xs shadow-xs transition flex items-center gap-2 disabled:opacity-50 cursor-pointer"
              >
                {loading ? "Saving..." : initialLocation ? "Update Station" : "Save Station"}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
